#
# Software Name : free5gc-kubernetes
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# Default values for free5gcControlPlane chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
  projectName: free5gc
  nrf:
    service:
      name: nrf-nnrf
      type: ClusterIP
      port: 80
      nodePort: "30800"
  sbi:
    scheme: http

initcontainers:
  curl:
    registry: towards5gs
    image: initcurl
    tag: "1.0.0"
  busybox:
    image: busybox
    tag: "1.32.0"

controller:
  name: controller
  image: carlossssssss/controller
  tag: latest
  service:
    type: ClusterIP
    port: 9999
  env:
    NF_TYPE: nssf
    ISSUER_DID: "J2168i1E7NNH3T1ZAtowHx"
    SCHEMA_ID: "J2168i1E7NNH3T1ZAtowHx:2:auth:1.9"
    CRED_DEF_ID: "J2168i1E7NNH3T1ZAtowHx:3:CL:45:default2"
    ACAPY_IP: "127.0.0.1"
    ACAPY_PORT: 7777
    APP_PORT: 9999
    DB_PORT: 5432
    NF_PORT: 80
    AMF_DID: "KQmkmEHAUb59MCBWGvHL8u"
    AUSF_DID: "Y3vuh72yVH3JPokz868i9L"
    NRF_DID: "S3SuLKgDtfALEshJLsQ6s5"
    NSSF_DID: "Wg2idaauZ9i2kQfRMUJh43"
    PCF_DID: "R2oSXYqQLZ1wTDBQHZZcMH"
    SMF_DID: "KGQpk9XCTeSb8iFUWRo61r"
    UDM_DID: "E2j1vjdsNg2fLYm58tqQH2"
    UDR_DID: "TrheLkYW2NK6RAEHNrZDxc"


database:
  name: database
  image: haidinhtuan/nf-db
  env:
    POSTGRES_PASSWORD: "postgres"

acapy:
  name: acapy
  image: bcgovimages/aries-cloudagent:py36-1.16-1_0.8.1
  env:
    ACAPY_ADMIN_INSECURE_MODE: "true"
    ACAPY_AUTO_PROVISION: "true"
    ACAPY_DEBUG_CONNECTIONS: "true"
    ACAPY_ENDPOINT: "http://free5gc-core-free5gc-nssf-acapy-service:5555"
    ACAPY_LABEL: "NSSF"
    ACAPY_LOG_LEVEL: "info"
    ACAPY_GENESIS_URL: "http://raw.githubusercontent.com/CarloSegat/free5gc-kubernetes-carlo/refs/heads/main/genesis.json"
    ADMIN_PORT: "7777"
    AGENT_PORT: "5555"
    SEED: "0123456789012345678901234567nssf"
  service: 
    type: ClusterIP
    port: 5555


nssf:
  name: nssf
  replicaCount: 1
  image:
    name: haidinhtuan/free5gc-nssf
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  volume:
    mount: /free5gc/config/
  podAnnotations: {}
    # additional annotations
  imagePullSecrets: []
  podSecurityContext: {}
  securityContext: {}
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 1
    timeoutSeconds: 1
    failureThreshold:  40
    successThreshold: 1
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  configuration:
    serviceNameList: |-
      - nnssf-nsselection
      - nnssf-nssaiavailability
    configuration: |-
      nssfName: NSSF
      supportedPlmnList:
        - mcc: 208
          mnc: 93
      supportedNssaiInPlmnList:
        - plmnId:
            mcc: 208
            mnc: 93
          supportedSnssaiList:
            - sst: 1
              sd: 010203
            - sst: 1
              sd: 112233
            - sst: 1
              sd: 3
            - sst: 2
              sd: 1
            - sst: 2
              sd: 2
      amfList:
        - nfId: 469de254-2fe5-4ca0-8381-af3f500af77c
          supportedNssaiAvailabilityData:
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33456
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 2
                - sst: 2
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33457
              supportedSnssaiList:
                - sst: 1
                  sd: 1
                - sst: 1
                  sd: 2
        - nfId: fbe604a8-27b2-417e-bd7c-8a7be2691f8d
          supportedNssaiAvailabilityData:
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33458
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 1
                - sst: 1
                  sd: 3
                - sst: 2
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33459
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 1
                - sst: 2
                - sst: 2
                  sd: 1
        - nfId: b9e6e2cb-5ce8-4cb6-9173-a266dd9a2f0c
          supportedNssaiAvailabilityData:
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33456
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 1
                - sst: 1
                  sd: 2
                - sst: 2
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33458
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 1
                - sst: 2
                - sst: 2
                  sd: 1
      taList:
        - tai:
            plmnId:
              mcc: 466
              mnc: 92
            tac: 33456
          accessType: 3GPP_ACCESS
          supportedSnssaiList:
            - sst: 1
            - sst: 1
              sd: 1
            - sst: 1
              sd: 2
            - sst: 2
        - tai:
            plmnId:
              mcc: 466
              mnc: 92
            tac: 33457
          accessType: 3GPP_ACCESS
          supportedSnssaiList:
            - sst: 1
            - sst: 1
              sd: 1
            - sst: 1
              sd: 2
            - sst: 2
        - tai:
            plmnId:
              mcc: 466
              mnc: 92
            tac: 33458
          accessType: 3GPP_ACCESS
          supportedSnssaiList:
            - sst: 1
            - sst: 1
              sd: 1
            - sst: 1
              sd: 3
            - sst: 2
          restrictedSnssaiList:
            - homePlmnId:
                mcc: 310
                mnc: 560
              sNssaiList:
                - sst: 1
                  sd: 3
        - tai:
            plmnId:
              mcc: 466
              mnc: 92
            tac: 33459
          accessType: 3GPP_ACCESS
          supportedSnssaiList:
            - sst: 1
            - sst: 1
              sd: 1
            - sst: 2
            - sst: 2
              sd: 1
          restrictedSnssaiList:
            - homePlmnId:
                mcc: 310
                mnc: 560
              sNssaiList:
                - sst: 2
                  sd: 1
      mappingListFromPlmn:
        - operatorName: NTT Docomo
          homePlmnId:
            mcc: 440
            mnc: 10
          mappingOfSnssai:
            - servingSnssai:
                sst: 1
                sd: 1
              homeSnssai:
                sst: 1
                sd: 1
            - servingSnssai:
                sst: 1
                sd: 2
              homeSnssai:
                sst: 1
                sd: 3
            - servingSnssai:
                sst: 1
                sd: 3
              homeSnssai:
                sst: 1
                sd: 4
            - servingSnssai:
                sst: 2
                sd: 1
              homeSnssai:
                sst: 2
                sd: 2
        - operatorName: AT&T Mobility
          homePlmnId:
            mcc: 310
            mnc: 560
          mappingOfSnssai:
            - servingSnssai:
                sst: 1
                sd: 1
              homeSnssai:
                sst: 1
                sd: 2
            - servingSnssai:
                sst: 1
                sd: 2
              homeSnssai:
                sst: 1
                sd: 3
    # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
    logger:
      NSSF:
        debugLevel: info
        ReportCaller: false
hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "ausf.snet.tuberlin"
    - "amf.snet.tuberlin"
    - "pcf.snet.tuberlin"
    - "smf.snet.tuberlin"
    - "udm.snet.tuberlin"
    - "udr.snet.tuberlin"
    - "upf.snet.tuberlin"
