#
# Software Name : free5gc-kubernetes
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/free5gc-kubernetes/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# Default values for free5gcControlPlane chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
  projectName: free5gc
  nrf:
    service:
      name: nrf-nnrf
      type: ClusterIP
      port: 9999
      nodePort: "30800"
  sbi:
    scheme: http

initcontainers:
  curl:
    registry: towards5gs
    image: initcurl
    tag: "1.0.0"
  busybox:
    image: busybox
    tag: "1.32.0"

db:
  enabled: true
# This section can be used to override the default values in the MongoDB chart (remember MongoDB is a subchart of the free5gcControlplane chart since control plane NFs rely on it.
mongodb:
  fullnameOverride: "mongodb"
  useStatefulSet: true
  auth:
    enabled: false
  persistence:
    size: 6Gi
    mountPath: /bitnami/mongodb/data/db/
  service:
    name: mongodb
    type: ClusterIP
    port: 27017
    nodePort: "30017"

controller:
  name: controller
  image: haidinhtuan/controller
  tag: latest
  service:
    type: ClusterIP
    port: 9999
  env:
    NF_TYPE: nrf
    ISSUER_DID: "J2168i1E7NNH3T1ZAtowHx"
    SCHEMA_ID: "J2168i1E7NNH3T1ZAtowHx:2:auth:1.1"
    CRED_DEF_ID: "J2168i1E7NNH3T1ZAtowHx:3:CL:14475:default"
    ACAPY_IP: "127.0.0.1"
    ACAPY_PORT: 7777
    APP_PORT: 9999
    DB_PORT: 5432
    NF_PORT: 80
    AMF_DID: "KQmkmEHAUb59MCBWGvHL8u"
    AUSF_DID: "Y3vuh72yVH3JPokz868i9L"
    NRF_DID: "S3SuLKgDtfALEshJLsQ6s5"
    NSSF_DID: "Wg2idaauZ9i2kQfRMUJh43"
    PCF_DID: "R2oSXYqQLZ1wTDBQHZZcMH"
    SMF_DID: "KGQpk9XCTeSb8iFUWRo61r"
    UDM_DID: "E2j1vjdsNg2fLYm58tqQH2"
    UDR_DID: "TrheLkYW2NK6RAEHNrZDxc"

database:
  name: database
  image: haidinhtuan/nf-db
  env:
    POSTGRES_PASSWORD: "postgres"

acapy:
  name: acapy
  image: bcgovimages/aries-cloudagent:py36-1.16-1_0.8.1
  env:
    ACAPY_ADMIN_INSECURE_MODE: "true"
    ACAPY_AUTO_PROVISION: "true"
    ACAPY_DEBUG_CONNECTIONS: "true"
    ACAPY_ENDPOINT: "http://free5gc-core-free5gc-nrf-acapy-service:5555"
    ACAPY_LABEL: "NRF"
    ACAPY_LOG_LEVEL: "info"
    ACAPY_GENESIS_URL: "http://raw.githubusercontent.com/CarloSegat/free5gc-kubernetes-carlo/refs/heads/main/genesis.json"
    ADMIN_PORT: "7777"
    AGENT_PORT: "5555"
    SEED: "01234567890123456789012345678nrf"
  service: 
    type: ClusterIP
    port: 5555

nrf:
  name: nrf
  replicaCount: 1
  image:
    name: haidinhtuan/free5gc-nrf
    pullPolicy: Always
  volume:
    mount: /free5gc/config/
  podAnnotations: {}
    # additional annotations
  imagePullSecrets: []
  podSecurityContext: {}
  securityContext: {}
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 1
    timeoutSeconds: 1
    failureThreshold:  40
    successThreshold: 1
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  configuration:
    serviceNameList: |-
      - nnrf-nfm
      - nnrf-disc
    configuration: |-
      DefaultPlmnId:
        mcc: 208
        mnc: 93
    logger:
      NRF:
        debugLevel: info
        ReportCaller: false

sidecar:
  image: haidinhtuan/sidecar
  tag: latest
  service:
    type: ClusterIP
    port: 9999
