#
# Software Name : free5gc-kubernetes
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/free5gc-kubernetes/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# Default values for free5gcControlPlane chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

global:
  projectName: free5gc
  env:
    NF_TYPE: AMF  
  nrf:
    service:
      name: nrf-nnrf
      type: ClusterIP
      port: 80
      nodePort: "30800"
  sbi:
    scheme: http
  amf:
    n2if:  # NGAP
      ipAddress: 10.100.50.249
    service:
      ngap:
        enabled: false
        name: amf-n2
        port: 38412
        nodeport: 31412
        protocol: SCTP
        type: NodePort
  n2network:
    enabled: true
    name: n2network
    type: ipvlan
    masterIf: eth0
    subnetIP: 10.100.50.248
    cidr: 29
    gatewayIP: 10.100.50.254
    excludeIP: 10.100.50.254

initcontainers:
  curl:
    registry: towards5gs
    image: initcurl
    tag: "1.0.0"
  busybox:
    image: busybox
    tag: "1.32.0"

isNgapNeeded: true

controller:
  name: controller
  image: haidinhtuan/controller
  tag: latest
  service:
    type: ClusterIP
    port: 9999
  env:
    NF_TYPE: amf
    ISSUER_DID: "J2168i1E7NNH3T1ZAtowHx"
    SCHEMA_ID: "J2168i1E7NNH3T1ZAtowHx:2:auth:1.2"
    CRED_DEF_ID: "J2168i1E7NNH3T1ZAtowHx:3:CL:14475:default"
    ACAPY_IP: "127.0.0.1"
    ACAPY_PORT: 7777
    APP_PORT: 9999
    DB_PORT: 5432
    NF_PORT: 80
    AMF_DID: "KQmkmEHAUb59MCBWGvHL8u"
    AUSF_DID: "Y3vuh72yVH3JPokz868i9L"
    NRF_DID: "S3SuLKgDtfALEshJLsQ6s5"
    NSSF_DID: "Wg2idaauZ9i2kQfRMUJh43"
    PCF_DID: "R2oSXYqQLZ1wTDBQHZZcMH"
    SMF_DID: "KGQpk9XCTeSb8iFUWRo61r"
    UDM_DID: "E2j1vjdsNg2fLYm58tqQH2"
    UDR_DID: "TrheLkYW2NK6RAEHNrZDxc"


database:
  name: database
  image: haidinhtuan/nf-db
  env:
    POSTGRES_PASSWORD: "postgres"

acapy:
  name: acapy
  image: bcgovimages/aries-cloudagent:py36-1.16-1_0.8.1
  env:
    ACAPY_ADMIN_INSECURE_MODE: "true"
    ACAPY_AUTO_PROVISION: "true"
    ACAPY_DEBUG_CONNECTIONS: "true"
    ACAPY_ENDPOINT: "http://free5gc-core-free5gc-amf-acapy-service:5555"
    ACAPY_LABEL: "AMF"
    ACAPY_LOG_LEVEL: "info"
    ACAPY_GENESIS_URL: "http://raw.githubusercontent.com/CarloSegat/free5gc-kubernetes-carlo/refs/heads/main/genesis.json"
    ADMIN_PORT: "7777"
    AGENT_PORT: "5555"
    SEED: "01234567890123456789012345678amf"
  service: 
    type: ClusterIP
    port: 5555

amf:
  name: amf
  replicaCount: 1
  image:
    name: haidinhtuan/free5gc-amf
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  volume:
    mount: /free5gc/config/
  podAnnotations: {}
    # additional annotations
  imagePullSecrets: []
  podSecurityContext: {}
  securityContext: {}
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 1
    timeoutSeconds: 1
    failureThreshold:  40
    successThreshold: 1
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  configuration:
    serviceNameList: |-
        - namf-comm
        - namf-evts
        - namf-mt
        - namf-loc
        - namf-oam
    configuration: |-
      amfName: AMF
      serviceNameList:
        - namf-comm
        - namf-evts
        - namf-mt
        - namf-loc
        - namf-oam
      servedGuamiList:
        - plmnId:
            mcc: 208
            mnc: 93
          amfId: cafe00
      supportTaiList:
        - plmnId:
            mcc: 208
            mnc: 93
          tac: 1
      plmnSupportList:
        - plmnId:
            mcc: 208
            mnc: 93
          snssaiList:
            - sst: 1
              sd: 010203
            - sst: 1
              sd: 112233
      supportDnnList:
        - internet
      security:
        integrityOrder:
          - NIA2
        cipheringOrder:
          - NEA0
      networkName:
        full: free5GC
        short: free
      locality: area1 # Name of the location where a set of AMF, SMF and UPFs are located
      networkFeatureSupport5GS: # 5gs Network Feature Support IE, refer to TS 24.501
        enable: true # append this IE in Registration accept or not
        length: 1 # IE content length (uinteger, range: 1~3)
        imsVoPS: 0 # IMS voice over PS session indicator (uinteger, range: 0~1)
        emc: 0 # Emergency service support indicator for 3GPP access (uinteger, range: 0~3)
        emf: 0 # Emergency service fallback indicator for 3GPP access (uinteger, range: 0~3)
        iwkN26: 0 # Interworking without N26 interface indicator (uinteger, range: 0~1)
        mpsi: 0 # MPS indicator (uinteger, range: 0~1)
        emcN3: 0 # Emergency service support indicator for Non-3GPP access (uinteger, range: 0~1)
        mcsi: 0 # MCS indicator (uinteger, range: 0~1)
      t3502Value: 720
      t3512Value: 3600
      non3gppDeregistrationTimerValue: 3240
      # retransmission timer for paging message
      t3513:
        enable: true     # true or false
        expireTime: 60s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Registration Accept message
      t3522:
        enable: true     # true or false
        expireTime: 60s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Registration Accept message
      t3550:
        enable: true     # true or false
        expireTime: 60s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Authentication Request/Security Mode Command message
      t3560:
        enable: true     # true or false
        expireTime: 60s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Notification message
      t3565:
        enable: true     # true or false
        expireTime: 60s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      t3570:
        enable: true     # true or false
        expireTime: 60s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
    # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
    logger:
      AMF:
        debugLevel: info
        ReportCaller: false
      NAS:
        debugLevel: info
        ReportCaller: false
      FSM:
        debugLevel: info
        ReportCaller: false
      NGAP:
        debugLevel: info
        ReportCaller: false
      Aper:
        debugLevel: info
        ReportCaller: false
hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "ausf.snet.tuberlin"
    - "nssf.snet.tuberlin"
    - "pcf.snet.tuberlin"
    - "smf.snet.tuberlin"
    - "udm.snet.tuberlin"
    - "udr.snet.tuberlin"
    - "upf.snet.tuberlin"

